/* Simulation code for Project_ev.Electrcal_Vehicle_DEV.Map_based_model generated by the OpenModelica Compiler OpenModelica v1.18.1 (64-bit). */
#if !defined(Map_based_model__MODEL_H)
#define Map_based_model__MODEL_H

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_json.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "util/parallel_helper.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"
#include "simulation/solver/spatialDistribution.h"

#if defined(__cplusplus)
extern "C" {
#endif

#include <string.h>

#include "Map_based_model_functions.h"

#define Modelica_Blocks_Tables_Internal_getNextTimeEvent_index 0
#define Modelica_Blocks_Tables_Internal_getTable2DAbscissaUmax_index 1
#define Modelica_Blocks_Tables_Internal_getTable2DAbscissaUmin_index 2
#define Modelica_Blocks_Tables_Internal_getTable2DValueNoDer2_index 3
#define Modelica_Blocks_Tables_Internal_getTimeTableTmax_index 4
#define Modelica_Blocks_Tables_Internal_getTimeTableTmin_index 5
#define Modelica_Blocks_Tables_Internal_getTimeTableValueNoDer2_index 6
#define Modelica_Blocks_Types_ExternalCombiTable2D_constructor_index 7
#define Modelica_Blocks_Types_ExternalCombiTable2D_destructor_index 8
#define Modelica_Blocks_Types_ExternalCombiTimeTable_constructor_index 9
#define Modelica_Blocks_Types_ExternalCombiTimeTable_destructor_index 10
#define Modelica_Utilities_Strings_isEmpty_index 11
#define Modelica_Utilities_Strings_length_index 12
#define Modelica_Utilities_Strings_Advanced_skipWhiteSpace_index 13

extern void Map_based_model_callExternalObjectDestructors(DATA *_data, threadData_t *threadData);
#if !defined(OMC_NUM_NONLINEAR_SYSTEMS) || OMC_NUM_NONLINEAR_SYSTEMS>0
extern void Map_based_model_initialNonLinearSystem(int nNonLinearSystems, NONLINEAR_SYSTEM_DATA *data);
#endif
#if !defined(OMC_NUM_LINEAR_SYSTEMS) || OMC_NUM_LINEAR_SYSTEMS>0
extern void Map_based_model_initialLinearSystem(int nLinearSystems, LINEAR_SYSTEM_DATA *data);
#endif
#if !defined(OMC_NUM_MIXED_SYSTEMS) || OMC_NUM_MIXED_SYSTEMS>0
#endif
#if !defined(OMC_NO_STATESELECTION)
extern void Map_based_model_initializeStateSets(int nStateSets, STATE_SET_DATA* statesetData, DATA *data);
#endif
extern int Map_based_model_functionAlgebraics(DATA *data, threadData_t *threadData);
extern int Map_based_model_function_storeDelayed(DATA *data, threadData_t *threadData);
extern int Map_based_model_function_storeSpatialDistribution(DATA *data, threadData_t *threadData);
extern int Map_based_model_function_initSpatialDistribution(DATA *data, threadData_t *threadData);
extern int Map_based_model_updateBoundVariableAttributes(DATA *data, threadData_t *threadData);
extern int Map_based_model_functionInitialEquations(DATA *data, threadData_t *threadData);
extern int Map_based_model_functionInitialEquations_lambda0(DATA *data, threadData_t *threadData);
extern int Map_based_model_functionRemovedInitialEquations(DATA *data, threadData_t *threadData);
extern int Map_based_model_updateBoundParameters(DATA *data, threadData_t *threadData);
extern int Map_based_model_checkForAsserts(DATA *data, threadData_t *threadData);
extern int Map_based_model_function_ZeroCrossingsEquations(DATA *data, threadData_t *threadData);
extern int Map_based_model_function_ZeroCrossings(DATA *data, threadData_t *threadData, double* gout);
extern int Map_based_model_function_updateRelations(DATA *data, threadData_t *threadData, int evalZeroCross);
extern const char* Map_based_model_zeroCrossingDescription(int i, int **out_EquationIndexes);
extern const char* Map_based_model_relationDescription(int i);
extern void Map_based_model_function_initSample(DATA *data, threadData_t *threadData);
extern int Map_based_model_initialAnalyticJacobianG(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Map_based_model_initialAnalyticJacobianA(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Map_based_model_initialAnalyticJacobianB(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Map_based_model_initialAnalyticJacobianC(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Map_based_model_initialAnalyticJacobianD(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Map_based_model_initialAnalyticJacobianF(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Map_based_model_functionJacG_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int Map_based_model_functionJacA_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int Map_based_model_functionJacB_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int Map_based_model_functionJacC_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int Map_based_model_functionJacD_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int Map_based_model_functionJacF_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern const char* Map_based_model_linear_model_frame(void);
extern const char* Map_based_model_linear_model_datarecovery_frame(void);
extern int Map_based_model_mayer(DATA* data, modelica_real** res, short *);
extern int Map_based_model_lagrange(DATA* data, modelica_real** res, short *, short *);
extern int Map_based_model_pickUpBoundsForInputsInOptimization(DATA* data, modelica_real* min, modelica_real* max, modelica_real*nominal, modelica_boolean *useNominal, char ** name, modelica_real * start, modelica_real * startTimeOpt);
extern int Map_based_model_setInputData(DATA *data, const modelica_boolean file);
extern int Map_based_model_getTimeGrid(DATA *data, modelica_integer * nsi, modelica_real**t);
extern void Map_based_model_function_initSynchronous(DATA * data, threadData_t *threadData);
extern void Map_based_model_function_updateSynchronous(DATA * data, threadData_t *threadData, long clockIndex);
extern int Map_based_model_function_equationsSynchronous(DATA * data, threadData_t *threadData, long clockIndex);
extern void Map_based_model_read_input_fmu(MODEL_DATA* modelData, SIMULATION_INFO* simulationData);
extern void Map_based_model_function_savePreSynchronous(DATA *data, threadData_t *threadData);
extern int Map_based_model_inputNames(DATA* data, char ** names);
extern int Map_based_model_dataReconciliationInputNames(DATA* data, char ** names);
extern int Map_based_model_initializeDAEmodeData(DATA *data, DAEMODE_DATA*);
extern int Map_based_model_functionLocalKnownVars(DATA*, threadData_t*);
extern int Map_based_model_symbolicInlineSystem(DATA*, threadData_t*);

#include "Map_based_model_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#if defined(__cplusplus)
}
#endif

#endif /* !defined(Map_based_model__MODEL_H) */


