# Makefile generated by OpenModelica
# Platform: win64

# Simulations use -O3 by default
CC=clang
CXX=clang++
LINK=clang++ -shared -Xlinker --export-all-symbols
EXEEXT=.exe
DLLEXT=.dll
CFLAGS_BASED_ON_INIT_FILE=
# define OMC_CFLAGS_OPTIMIZATION env variable to your desired optimization level to override this
OMC_CFLAGS_OPTIMIZATION=-Os
DEBUG_FLAGS=$(OMC_CFLAGS_OPTIMIZATION)
CFLAGS=$(CFLAGS_BASED_ON_INIT_FILE) $(DEBUG_FLAGS) -Wno-parentheses-equality -falign-functions -mstackrealign -msse2 -mfpmath=sse ${MODELICAUSERCFLAGS}   
CPPFLAGS="-IC:/Program Files/OpenModelica1.18.1-64bit/lib/omlibrary/Modelica 4.0.0/Resources/C-Sources" -I"C:/Program Files/OpenModelica1.18.1-64bit/include/omc/c" -I. -DOPENMODELICA_XML_FROM_FILE_AT_RUNTIME -DOMC_MODEL_PREFIX=Map_based_model -DOMC_NUM_MIXED_SYSTEMS=0 -DOMC_NUM_LINEAR_SYSTEMS=1 -DOMC_NUM_NONLINEAR_SYSTEMS=5 -DOMC_NDELAY_EXPRESSIONS=0 -DOMC_NVAR_STRING=0
# define OMC_LDFLAGS_LINK_TYPE env variable to "static" to override this
OMC_LDFLAGS_LINK_TYPE=dynamic
RUNTIME_LIBS= -Wl,-B$(OMC_LDFLAGS_LINK_TYPE) -lSimulationRuntimeC -Wl,-Bdynamic  -Wl,-B$(OMC_LDFLAGS_LINK_TYPE) -lomcgc -lregex -ltre -lintl -liconv -lexpat -static-libgcc -luuid -loleaut32 -lole32 -limagehlp -lws2_32 -llis -lsundials_nvecserial -lsundials_sunmatrixdense -lsundials_sunmatrixsparse -lsundials_sunlinsoldense -lsundials_sunlinsolklu -lsundials_sunlinsollapackdense -lsundials_sunlinsolspbcgs -lsundials_sunlinsolspfgmr -lsundials_sunlinsolspgmr -lsundials_sunlinsolsptfqmr -lsundials_sunnonlinsolnewton -lsundials_cvode -lsundials_cvodes -lsundials_idas -lsundials_kinsol -lumfpack -lklu -lcolamd -lbtf -lamd -lsuitesparseconfig -lipopt -lcoinmumps -lpthread -lm  -lgfortran -lquadmath -lmingw32 -lgcc_eh -lmoldname -lmingwex  -luser32 -lkernel32 -ladvapi32 -lshell32 -lopenblas -lcminpack -Wl,-Bdynamic -lwsock32  -Wl,-B$(OMC_LDFLAGS_LINK_TYPE)  -lstdc++ -Wl,-Bdynamic 
LDFLAGS=-L"C:/Program Files/OpenModelica1.18.1-64bit/lib//omc" -L"C:/Program Files/OpenModelica1.18.1-64bit/lib" -Wl,--stack,16777216,-rpath,"C:/Program Files/OpenModelica1.18.1-64bit/lib//omc" -Wl,-rpath,"C:/Program Files/OpenModelica1.18.1-64bit/lib"  -fopenmp -Wl,-Bstatic -lregex -ltre -lintl -liconv -lexpat -lomcgc -lpthread -loleaut32 -limagehlp -lhdf5 -lz -lszip -Wl,-Bdynamic $(RUNTIME_LIBS) 
DIREXTRA=-L"C:/Users/SH REHEMAN/Desktop"
MAINFILE=Map_based_model.c
MAINOBJ=Map_based_model.o
CFILES=Map_based_model_functions.c Map_based_model_records.c \
Map_based_model_01exo.c Map_based_model_02nls.c Map_based_model_03lsy.c Map_based_model_04set.c Map_based_model_05evt.c Map_based_model_06inz.c Map_based_model_07dly.c \
Map_based_model_08bnd.c Map_based_model_09alg.c Map_based_model_10asr.c Map_based_model_11mix.c Map_based_model_12jac.c Map_based_model_13opt.c Map_based_model_14lnz.c \
Map_based_model_15syn.c Map_based_model_16dae.c Map_based_model_17inl.c Map_based_model_18spd.c 

OFILES=$(CFILES:.c=.o)
GENERATEDFILES=$(MAINFILE) Map_based_model.makefile Map_based_model_literals.h Map_based_model_functions.h $(CFILES)

.PHONY: omc_main_target clean bundle

# This is to make sure that Map_based_model_*.c are always compiled.
.PHONY: $(CFILES)

omc_main_target: $(MAINOBJ) Map_based_model_functions.h Map_based_model_literals.h $(OFILES)
	$(CC) -I. -o Map_based_model$(EXEEXT) $(MAINOBJ) $(OFILES) $(CPPFLAGS) $(DIREXTRA)  "-LC:/Program Files/OpenModelica1.18.1-64bit/lib//omc" "-LC:/Program Files/OpenModelica1.18.1-64bit/lib/" "-LC:/Users/SH REHEMAN/AppData/Roaming/.openmodelica/binaries/Modelica" "-LC:/Program Files/OpenModelica1.18.1-64bit/lib/omlibrary/Modelica 4.0.0/Resources/Library/mingw64" "-LC:/Program Files/OpenModelica1.18.1-64bit/lib/omlibrary/Modelica 4.0.0/Resources/Library/win64" "-LC:/Program Files/OpenModelica1.18.1-64bit/lib/omlibrary/Modelica 4.0.0/Resources/Library" -lModelicaExternalC -lModelicaStandardTables -lModelicaIO -lModelicaMatIO -lzlib $(CFLAGS) $(CPPFLAGS) $(LDFLAGS)
clean:
	@rm -f Map_based_model_records.o $(MAINOBJ)

bundle:
	@tar -cvf Map_based_model_Files.tar $(GENERATEDFILES)